### ISSUE TITLE
Outdoor mines now move! But clip themselves through the ground eventually?

### ISSUE THREAD

**Issue by Roobotics** [74oshua/RoombaMines#3]
Upon testing outdoor mines, they now seem to actually move after the last update.. kind of! 

They have separate issues it seems, I imagine indoors they follow a flat plane continuously, but outside, once they are aligned to a 'floor' region, I think they are clipping into adjacent terrain as it slopes up through that plane, or just confused that they have any tilt in the first place perhaps.. for a while I was watching one move around on a relatively flat area, successfully I might add, but then eventually..

They all do this weird little orbit-in-place movement on multiple axis(not just spinning in a circle like a roomba should), sometimes while doing this, they clip further through the ground at random, and never really come back up afterwards. They might be driving 'down' after rotating like this.

Orbiting:
![20240211003859_1](https://github.com/74oshua/RoombaMines/assets/6250768/ee84c67c-e4a0-4216-ab2e-91406e19ca9d)
![20240211003900_1](https://github.com/74oshua/RoombaMines/assets/6250768/401aaabd-cfd0-4a65-b6d7-6ad10297ee95)
![20240211003902_1](https://github.com/74oshua/RoombaMines/assets/6250768/492d9056-4fab-41b9-b3da-267047249c78)

And sometimes they make a tiny little 'warp' and are instantaneously beside their old location. This might be what's clipping them through, unsure!
![20240211003906_1](https://github.com/74oshua/RoombaMines/assets/6250768/20b5492d-d63f-4fb8-8d43-88f68f6d71cb)

Unless you are going to update the pathing to let them work outside with angled terrain, I'd suggest disabling the outside spawns from being moving roombas if that's realistically possible. If you do intend to make them to work and they can be differentiated, please let them have an alternative speed/spin configuration if that's within reason, understandable if not at this time!

A few different mods spawn outside mines, I've tested this with 'HazardsOutside' as it does it consistently and is configurable to guarantee you will see a lot of them if needed. But special event mods like 'Brutal_Company' also have events that do things like this at random as well, so I don't think it will be an isolated occurrence.

**Comment by 74oshua** [comment]
To be clear, mines only spawn outside when additional mods are installed that allow them to spawn outside, correct? If so, I'll mark this as a feature request.

**Comment by Roobotics** [comment]
That is correct, there's a few different mods that spawn mines and/or turrets outside. I understand if it's not in your scope to have this be compatible at this time, rather letting you know it likely occurs in the other instances as well. So yes, very much a feature request otherwise!

**Comment by 74oshua** [comment]
@Roobotics Got it. I'll likely just have the mines remain stationary if they're outside, once I figure out how to determine that...

**Comment by Roobotics** [comment]
@74oshua From what I understand about the game. Generated rooms are (possibly)stacked under the map where the ship lands(so when you go inside, you aren't loading a new area, just warping under to the main entrance), so if that's at a consistent z-depth and you can know that  for each roomba, perhaps you could disable all movement on mines well above a reasonably generating room height.

Of course an instanced name or class to hook into like "outside.mine" or similar would be more practical, it's probably harder to say if the various mods that do spawn these, would name them with the same conventions.

**Comment by 74oshua** [comment]
@Roobotics 1.1.4 has a fix based on the world height, thanks for the suggestion

**Comment by Roobotics** [comment]
@74oshua that seems to be working as intended! I've been able to run across a few different moons and the mines outside have all stayed where expected. I'd say this one is solved as well, you now have compatibility with a lot of other mods!
