### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by Vicerek** [74oshua/RoombaMines#4]
Not much of an issue, maybe it was supposed to be like that but just saying that the log now looks like that: 
![image](https://github.com/74oshua/RoombaMines/assets/115656580/7d1ab4da-f153-4797-8a87-d58cca8f0366)

It doesn't cause any lag or anything. So it doesn't affect the gameplay. The amount of the lines depends of how many mines there are in the facility and it spams them for the whole duration of being on the moon. I'm guessing that that's just checking what stepped on the mine and if its not a player then it doesn't explode? Similar thing was happening when the mines spawned next to the ship but it doesn't cause lag like then.

**Comment by 74oshua** [comment]
That's part of the unmodded game, the game prints a line in the log any time ANY collider is on top of a mine, even if that collider isn't on a layer that would make a mine detonate.

I agree it's annoying, but I want to keep the actual landmine detonation behavior unmodified in case it's changed in a later update. Hopefully the Lethal dev goes through and prunes some of these unnecessary Debug.Logs
